services:
  dev:
    container_name: my-portfolio-dev
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - "5172:5172"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
