services:
  web:
    container_name: my-portfolio
    image: cepiseptiyana/my-portfolio:latest
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile
      target: production
    ports:
      - "8080:80"
    restart: always